// Cache Debugger's functions
#define dbg_cache_hit(base)        (*(volatile int*)  (base+0x000))
#define dbg_cache_miss(base)       (*(volatile int*)  (base+0x004))
#define dbg_instr_hit(base)        (*(volatile int*)  (base+0x008))
#define dbg_instr_miss(base)       (*(volatile int*)  (base+0x00C))
#define dbg_data_hit(base)         (*(volatile int*)  (base+0x010))
#define dbg_data_miss(base)        (*(volatile int*)  (base+0x014))
#define dbg_data_read_hit(base)    (*(volatile int*)  (base+0x018))
#define dbg_data_read_miss(base)   (*(volatile int*)  (base+0x01C))
#define dbg_data_write_hit(base)   (*(volatile int*)  (base+0x020))
#define dbg_data_write_miss(base)  (*(volatile int*)  (base+0x024))
#define dbg_counter_reset(base)    (*(volatile int*)  (base+0x028))
#define dbg_cache_invalidate(base) (*(volatile int*)  (base+0x02C))
#define dbg_clock_start(base)      (*(volatile int*)  (base+0x030))
#define dbg_clock_stop(base)       (*(volatile int*)  (base+0x034))
#define dbg_clock_upper(base)      (*(volatile int*)  (base+0x038))
#define dbg_clock_lower(base)      (*(volatile int*)  (base+0x03C))
