VERSION ?=0010
DATA_W ?= 32
ADDR_W ?= 15
BE_DATA_W ?= 64
BE_ADDR_W ?= 24
NWAYS_W ?= 1
NLINES_W ?= 7
WORD_OFFSET_W ?= 3
WTBUF_DEPTH_W ?= 4
REP_POLICY ?=0
WRITE_POL ?= 0
CTRL_CACHE ?= 0
CTRL_CNT ?= 0
AXI ?= 1

MACRO_LIST += DATA_W ADDR_W BE_DATA_W BE_ADDR_W NWAYS_W NLINES_W WORD_OFFSET_W WTBUF_DEPTH_W REP_POLICY WRITE_POL CTRL_CACHE CTRL_CNT AXI
