CORE_NAME:=CACHE
IS_CORE:=1
USE_NETLIST ?=0

#submodules
ifneq (MEM,$(filter M, $(SUBMODULES)))
LOCAL_SUBMODULES = MEM
MEM_DIR ?=$(CORE_NAME)_DIR/submodules/MEM
endif

ifneq (INTERCON,$(filter M, $(SUBMODULES)))
LOCAL_SUBMODULES+=INTERCON
INTERCON_DIR ?=$(CORE_NAME)_DIR/submodules/INTERCON
endif

ifneq (AXIMEM,$(filter M, $(SUBMODULES)))
LOCAL_SUBMODULES+=AXIMEM
AXIMEM_DIR ?=$(CORE_NAME)_DIR/submodules/AXIMEM
endif

SUBMODULES+=LOCAL_SUBMODULES
