[['']]
WTB_EMPTY = {rw_type="R", nbits=1, rst_val=0, addr=0, addr_w=0, autologic=false, description="Write-through buffer empty (1) or non-empty (0)."} 
WTB_FULL = {rw_type="R", nbits=1, rst_val=0, addr=1, addr_w=0, autologic=false, description="Write-through buffer full (1) or non-full (0)."} 
RW_HIT = {rw_type="R", nbits=32, rst_val=0, addr=4, addr_w=0, autologic=false, description="Read and write hit counter."}
RW_MISS = {rw_type="R", nbits=32, rst_val=0, addr=8, addr_w=0, autologic=false, description="Read and write miss counter."}
READ_HIT = {rw_type="R", nbits=32, rst_val=0, addr=12, addr_w=0, autologic=false, description="Read hit counter."}
READ_MISS = {rw_type="R", nbits=32, rst_val=0, addr=16, addr_w=0, autologic=false, description="Read miss counter."}
WRITE_HIT = {rw_type="R", nbits=32, rst_val=0, addr=20, addr_w=0, autologic=false, description="Write hit counter."}
WRITE_MISS = {rw_type="R", nbits=32, rst_val=0, addr=24, addr_w=0, autologic=false, description="Write miss counter."}
RST_CNTRS = {rw_type="W", nbits=1, rst_val=0, addr=28, addr_w=0, autologic=false, description="Reset read/write hit/miss counters by writing any value to this register."}
INVALIDATE = {rw_type="W", nbits=1, rst_val=0, addr=32, addr_w=0, autologic=false, description="Invalidate the cache data contents by writing any value to this register."}
VERSION = {rw_type="R", nbits=32, rst_val=0, addr=36, addr_w=0, autologic=false, description="Cache version."}
