CACHE_DIR:=../..
include $(CACHE_DIR)/config.mk

ROOT_DIR:=../..
include $(ROOT_DIR)/submodules/LIB/hardware/fpga/fpga.mk

NOCLEAN:= -name 'Makefile' -o -name 'iob_cache.xdc' -o -name 'iob_cache.sdc' 
