name: CI

# Set default shell as interactive (source ~/.bashrc)
defaults:
  run:
    shell: bash -ieo pipefail {0}

on:
  push:
    branches: 
      - master
      - doc
  # Don't forget to require approval for all outside collaborators
  pull_request:
    branches: '*'
  # Allow manual workflow runs
  workflow_dispatch:

# Run only one instance of this workflow at a time
# cancel-in-progress: stop running workflow and run latest instead
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sim:
    runs-on: self-hosted
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: test-clean
        run: make test-clean
      - name: test-sim
        run: make test-sim

  fpga:
    runs-on: self-hosted
    timeout-minutes: 30
    # run even if previous job failed
    if: ${{ always() }}
    # run after indicated job
    needs: sim

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: test-clean
        run: make test-clean
      - name: test-fpga
        run: make test-fpga

  doc:
    runs-on: self-hosted
    timeout-minutes: 30
    # run even if previous job failed
    if: ${{ always() }}
    # run after indicated job
    needs: fpga

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: test-clean
        run: make test-clean
      - name: test-doc
        run: make test-doc
