name: CI

# Set default shell as interactive (source ~/.bashrc)
defaults:
  run:
    shell: bash -ieo pipefail {0}

on:
  push:
    branches: 
      - master
      - build-lib
  # Don't forget to require approval for all outside collaborators
  pull_request:
    branches: '*'
  # Allow manual workflow runs
  workflow_dispatch:

# Run only one instance of this workflow at a time
# cancel-in-progress: stop running workflow and run latest instead
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sim:
    runs-on: self-hosted
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: setup
        run: make setup
      - name: test-sim
        run: make -C iob_cache_* sim-test

  fpga:
    runs-on: self-hosted
    timeout-minutes: 30
    # always run, except when previous job was cancelled
    if: ${{ !cancelled() }}
    # run after indicated job
    needs: sim

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: test-fpga
        run: make -C iob_cache_* fpga-test

  doc:
    runs-on: self-hosted
    timeout-minutes: 30
    # always run, except when previous job was cancelled
    if: ${{ !cancelled() }}
    # run after indicated job
    needs: fpga

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: test-doc
        run: make  -C iob_cache_* doc-test
