name: CI

# Set default shell as interactive (source ~/.bashrc)
defaults:
  run:
    shell: bash -ieo pipefail {0}

on:
  push:
    branches: 
      - master
      - build-lib
  # Don't forget to require approval for all outside collaborators
  pull_request:
    branches: '*'
  # Allow manual workflow runs
  workflow_dispatch:

# Run only one instance of this workflow at a time
# cancel-in-progress: stop running workflow and run latest instead
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  iob:
    runs-on: self-hosted
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: setup iob
        run: make clean && make setup CACHE_CONFIG=iob
      - name: sim-test iob
        run: make -C ../iob_cache_* sim-test
      - name: sim-clean
        run: make -C ../iob_cache_*sim-clean
      - name: test-fpga
        run: make -C ../iob_cache_* fpga-test
      - name: fpga-clean
        run: make -C ../iob_cache_* fpga-clean
      - name: test-doc
        run: make -C ../iob_cache_* doc-test
      - name: doc-clean
        run: make -C ../iob_cache_* doc-clean

  axi:
    runs-on: self-hosted
    timeout-minutes: 10
    # always run, except when previous job was cancelled
    if: ${{ !cancelled() }}
    # run after indicated job
    needs: iob

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: setup axi
        run: make clean && make setup CACHE_CONFIG=axi
      - name: sim-test iob
        run: make -C ../iob_cache_* sim-test
      - name: sim-clean
        run: make -C ../iob_cache_* sim-clean
      - name: test-fpga
        run: make -C ../iob_cache_* fpga-test
      - name: fpga-clean
        run: make -C ../iob_cache_* fpga-clean
      - name: test-doc
        run: make -C ../iob_cache_* doc-test
      - name: doc-clean
        run: make -C ../iob_cache_* doc-clean
